# services/db_port.py
from typing import Protocol, Dict, List, Optional

class DBPort(Protocol):
    # Patients
    def create_patient(self, data: Dict) -> str: ...
    def update_patient(self, patient_id: str, data: Dict) -> None: ...
    def get_patient(self, patient_id: str) -> Optional[Dict]: ...
    def find_patients(self, query: str) -> List[Dict]: ...
